src/retrieveCodeoutput/unpackaged/objects/Adaptive_Exam__c.object
<CustomObject>
    <fields>
        <fullName>Attempts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Attempts</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exam__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The base adaptive exam</inlineHelpText>
        <label>Adaptive Base Exam Number</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Exam__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Adaptive Exam</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Exam__c</referenceTo>
        <relationshipLabel>Adaptive Exams</relationshipLabel>
        <relationshipName>Adaptive_Exams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Number_of_questions__c</fullName>
        <defaultValue>10</defaultValue>
        <label>Number of questions</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Fail_Threshold__c</fullName>
        <defaultValue>0.25</defaultValue>
        <label>Question Fail Threshold</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Pass_Threshold__c</fullName>
        <defaultValue>0.85</defaultValue>
        <description>The average score must exceed this threshold for going to the next level</description>
        <label>Question Pass Threshold</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test_Taker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Taker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Adaptive Exams</relationshipLabel>
        <relationshipName>Adaptive_Exams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>DateTime</type>
    </fields>
    <label>Adaptive Exam</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>Adaptive Exam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adaptive Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/retrieveCodeoutput/unpackaged/objects/Exam__c.object
<CustomObject>
    <description>This is the base exam.  It has 3 record types for Standard Exam, Question Bank Exam and Adaptive Exam</description>
    <fields>
        <fullName>Number_of_questions__c</fullName>
        <label>Number of questions</label>
        <summaryForeignKey>Question__c.Exam__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Question_Bank_Exam__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank Exam</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Exam__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Question Bank</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Exam__c</referenceTo>
        <relationshipName>Exams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Base Exam</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Exam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Base Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/updateAdaptiveExam.cls
public class updateAdaptiveExam {
    @future(callout=true)
    public static void doUpdate(string recId) {
        adaptive_exam__c ae = [select id, exam__c, lastModifiedDate, attempts__c, number_of_questions__c, 
                               test_taker__c, question_pass_threshold__c, question_fail_threshold__c,
                               from__c, to__c from adaptive_exam__c where id = :recId];
        //if we want to use date check
        //Date start_date = ae.LastModifiedDate.date();
        //Date current_date = Date.today();
        //Integer days = start_date.daysBetween(current_date);
        //System.debug('Days:' + days);
        
        ae.attempts__c = 0;
        
        //delete the previous questions
        adaptiveTest.deleteOldQuestions(ae.id);
        String qbe_id = ae.exam__r.question_bank_exam__c;
        
        System.debug('Qbe:' + qbe_id + ', Test Taker:' + ae.Test_Taker__c + 
                     ', Question Pass Threshold:' + ae.Question_Pass_Threshold__c + ', Question Fail Threshold:' + ae.Question_Fail_Threshold__c +
                     ', From:' + ae.From__c + ', To:' + ae.To__c);
        Map<Object, Object> cmap = adaptiveTest.generateFilterCriteria(qbe_id, ae.Test_Taker__c, ae.Question_Pass_Threshold__c, ae.Question_Fail_Threshold__c, ae.from__c, ae.to__c);
        
        //store the map as json in the adaptive exam
        String cmapStr = adaptiveTest.map2jsonStr(cmap);
        if (cmapStr == null) {
            ae.Criteria__c = 'All questions';
        } else {
            ae.Criteria__c = cmapStr;
        }
        
        Integer number_of_questions = ae.number_of_questions__c.intValue();
        
        adaptiveTest.doGenerate(ae.id, qbe_id, cmap, number_of_questions);
        update(ae);
    }
}