src/retrieveCodeoutput/unpackaged/objects/Adaptive_Exam__c.object
<CustomObject>
    <fields>
        <fullName>Exam__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The base adaptive exam</inlineHelpText>
        <label>Adaptive Base Exam Number</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Exam__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Adaptive Exam</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Exam__c</referenceTo>
        <relationshipLabel>Adaptive Exams</relationshipLabel>
        <relationshipName>Adaptive_Exams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Taker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Taker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Adaptive Exams</relationshipLabel>
        <relationshipName>Adaptive_Exams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adaptive Exam</label>
    <nameField>
        <displayFormat>AE-{000000}</displayFormat>
        <label>Adaptive Exam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adaptive Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/retrieveCodeoutput/unpackaged/objects/Adaptive_Question__c.object
<CustomObject>
    <fields>
        <fullName>Adaptive_Exam__c</fullName>
        <label>Adaptive Exam</label>
        <referenceTo>Adaptive_Exam__c</referenceTo>
        <relationshipLabel>Adaptive Questions</relationshipLabel>
        <relationshipName>Adaptive_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Adaptive Questions</relationshipLabel>
        <relationshipName>Adaptive_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adaptive Question</label>
    <nameField>
        <displayFormat>AQ-{00000}</displayFormat>
        <label>Adaptive Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adaptive Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/retrieveCodeoutput/unpackaged/objects/Exam__c.object
<CustomObject>
    <description>This is the base exam.  It has 3 record types for Standard Exam, Question Bank Exam and Adaptive Exam</description>
    <label>Base Exam</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Exam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Base Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/retrieveCodeoutput/unpackaged/objects/Exam_Results_Detail__c.object
<CustomObject>
    <description>This has results of every question on every exam taken</description>
    <fields>
        <fullName>Exam__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exam</label>
        <referenceTo>Exam__c</referenceTo>
        <relationshipLabel>Exams Results Detail</relationshipLabel>
        <relationshipName>Exams_Results_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flex_Tag_1__c</fullName>
        <label>Flex Tag 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flex_Tag_2__c</fullName>
        <label>Flex Tag 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quest__c</fullName>
        <label>Quest</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test_Taker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Taker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Exams Results Detail</relationshipLabel>
        <relationshipName>Exams_Results_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exam Results Detail</label>
    <nameField>
        <label>Exam Results Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams Results Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/retrieveCodeoutput/unpackaged/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Exam__c</fullName>
        <label>Exam</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Exam__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>&quot;Standard Exam&quot;</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Exam__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Flex_Tag_1__c</fullName>
        <label>Flex Tag 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flex_Tag_2__c</fullName>
        <label>Flex Tag 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quest__c</fullName>
        <description>Holds the question</description>
        <label>Question Statement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/retrieveCodeoutput/unpackaged/classes/adaptiveTest.cls
public class adaptiveTest {

    public static void doGenerate(ID ae_id, String qbe_id, Map<Object, Object> cmap, Integer nq) {
		List<adaptive_question__c> aqList1 = new List<adaptive_question__c>();

        if (cmap.size() > 0) {
            for (Object t : cmap.keySet()) {
                //Select all the matching questions from question bank filtered by criteria and create a list
                String topic = String.valueOf(t);
                List<String> difficulty = (List<String>)(cmap.get(t));
                
                List<question__c> qList = [select id, quest__c, flex_tag_2__c from question__c where exam__c = :qbe_id and flex_tag_1__c = :topic and flex_tag_2__c in :difficulty];
                System.debug('Topic: ' + topic + ', Difficulty: ' + String.valueOf(difficulty) + ', qList size:' + qList.size());
                for (Question__c q : qList) {
                    adaptive_question__c aq = new adaptive_question__c(adaptive_exam__c = ae_id, question__c = q.Id);
                    aqList1.add(aq);
                }            
            }            
        } else {
            	//fetch all questions
                List<question__c> qList = [select id, quest__c, flex_tag_2__c from question__c where exam__c = :qbe_id];
                System.debug('qList size:' + qList.size());
                for (Question__c q : qList) {
                    adaptive_question__c aq = new adaptive_question__c(adaptive_exam__c = ae_id, question__c = q.Id);
                    aqList1.add(aq);
                }                        
        }
        system.debug('Aq List1:' + aqList1);
        
        //select questions randomly from this list to meet the required number of questions
		List<adaptive_question__c> aqList2 = new List<adaptive_question__c>();
        
        if (aqList1.size() > 0) {
            for (Integer ix=0; ix<nq; ix++) {
                Integer len = aqList1.size();
                Integer aqIndex = Integer.valueof((Math.random() * len));
                adaptive_question__c aq = aqList1.remove(aqIndex);
                System.debug('Removed question id:' + aq.question__c + ' from ' + aqIndex + ' of adaptive question list');
                aqList2.add(aq);            
            }
            
            insert(aqList2);            
        }
      
        system.debug('Succesfully generated ' + aqList2.size() + ' questions for adaptive exam:' + ae_id);
    }

    public static Map<Object, Object> generateFilterCriteria(String exam_id, String emp_id, Decimal max_threshold, Decimal min_threshold, Datetime fromDt, Datetime toDt) {
        AggregateResult[] agrList;
        
        if (fromDt == null && toDt == null) {
             agrList = [select flex_tag_1__c, flex_tag_2__c, avg(score__c)avg_score from exam_results_detail__c where test_taker__c = :emp_id and exam__c = :exam_id 
                        group by flex_tag_1__c, flex_tag_2__c];              
        }
        else if (fromDt != null && toDt == null) {
            agrList = [select flex_tag_1__c, flex_tag_2__c, avg(score__c)avg_score from exam_results_detail__c where test_taker__c = :emp_id and exam__c = :exam_id 
                       and lastModifiedDate >= :fromDt
                       group by flex_tag_1__c, flex_tag_2__c];          
        } else if (fromDt == null && toDt != null) {
            agrList = [select flex_tag_1__c, flex_tag_2__c, avg(score__c)avg_score from exam_results_detail__c where test_taker__c = :emp_id and exam__c = :exam_id 
                       and lastModifiedDate <= :toDt
                       group by flex_tag_1__c, flex_tag_2__c];                      
        } else {
             agrList = [select flex_tag_1__c, flex_tag_2__c, avg(score__c)avg_score from exam_results_detail__c where test_taker__c = :emp_id and exam__c = :exam_id 
                        and lastModifiedDate >= :fromDt and lastModifiedDate <= :toDt
                        group by flex_tag_1__c, flex_tag_2__c];           
        }
        
        // Topic	Difficulty	Avg Score
        // algebra 	1 			0.95
        // algebra 	2 			0.90
        // algebra 	3 			0.15
        // algebra 	4 			0.10
        // algebra 	5 			0.10
        // calculus 1 			0.92
        // calculus 2 			0.4
        // calculus 3 			0.7
        // calculus 4 			0.9
        // After applying criteria
        // algebra: [3, 4, 5] calculus: [2, 3, 5]
        
        System.debug('exam_id:' + exam_id + ', emp_id:' + emp_id);
        System.debug('agrList:' + agrList);
        Map<Object, Object> criteria_map = new Map<Object, Object>();
        
        List<String> d = null;

        for (AggregateResult ar : agrList) {
            Object topic = ar.get('flex_tag_1__c');
            Object level = ar.get('flex_tag_2__c');
            Object avg_score = ar.get('avg_score');
            System.debug('Topic:' + String.valueOf(topic));
            System.debug('Level:' + String.valueOf(level));
            System.debug('Avg Score:' + String.valueOf(avg_score));
			
            if (!criteria_map.containsKey(topic)) {
                //add all levels initially and remove as criteria are met
                d = new List<String>();
                d.add('1'); d.add('2'); d.add('3'); d.add('4'); d.add('5');
                criteria_map.put(topic, d);
                system.debug('Topic:' + topic + ' not present in criteria map');
                system.debug('Added default criteria:' + d);
            }
            
            //if score is >= than max threshold, remove this level in the criteria
            if (Double.valueOf(avg_score) >= max_threshold) {
                System.debug(avg_score + ' is >= ' + max_threshold);
                System.debug('Removing ' + level);
                d = (List<String>)criteria_map.get(topic);
                d.remove(d.indexOf(String.valueOf(level)));
                System.debug('List after removal of level:' + d);
            } else if (Double.valueOf(avg_score) < min_threshold) {
                    //if score is < min threshold, add the previous level back in the criteria
                    System.debug(avg_score + ' is < ' + min_threshold);
                    Integer int_level = Integer.valueOf(level);
                    if (int_level > 1) {
                        int_level = int_level - 1;
                        System.debug('Adding ' + int_level);
                        d = (List<String>)criteria_map.get(topic);
                        //add if not already present
                        if (!d.contains(String.valueof(int_level))) {
                            d.add(String.valueOf(int_level));
                            System.debug('List after addition of level:' + d);                                                            
                        }
                    }
                } else {
                    System.debug(avg_score + ' is >= ' + min_threshold + ' and < ' + max_threshold);
                }
            
            System.debug('Levels:' + d);

            //include questions from the lowest difficulty level - so ['3', '5', '4', '1'] will result in ['1']
            //if you need more levels, change the second argument from 1 to 2, 3 etc.
            List<String> lowestN = getLowestN(d, 1);
            System.debug('Topic:' + topic + ', LowestN:' + lowestN);
            criteria_map.put(topic, lowestN);
        }
              
        System.debug('Criteria Map:' + criteria_map);
        return criteria_map;
    }
     
    public static String map2jsonStr(Map<Object, Object> cmap) {
    	JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        for(Object t : cmap.keyset()) {
            String tstr = String.valueOf(t);
            List<String> difficulty = (List<String>)(cmap.get(t));
	        gen.writeObjectField(tstr, difficulty);           
        }
        gen.writeEndObject();
    	return gen.getAsString();
    }
    
    public static void deleteOldQuestions(ID ae_id) {
        List<adaptive_question__c> old_questions = [select id from adaptive_question__c where adaptive_exam__c = :ae_id];
        Integer num = old_questions.size();
        delete(old_questions);
        System.debug('Successfully deleted ' + num + ' old questions');
    }
    
    public static List<String> getLowestN(List<String> difficulty, Integer n) {
        //Returns the list of lowest N values
        List<String> lowestN = new List<String>();
        difficulty.sort();
        if (difficulty.size() < n) {
            return difficulty;
        } else {
            for(Integer i=0; i<n; i++) {
                lowestN.add(difficulty.get(i));
            }                    
	        return lowestN;
        }
    }
}