src/retrieveCodeoutput/unpackaged/objects/Certification__c.object
<CustomObject>
    <fields>
        <fullName>Certificate_ID__c</fullName>
        <label>Certificate ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Certification_Name__c</fullName>
        <label>Certification Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <label>Certification</label>
    <nameField>
        <displayFormat>CT-{00000}</displayFormat>
        <label>Certification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/retrieveCodeoutput/unpackaged/classes/FetchCertificationsController.cls
public class FetchCertificationsController {
    @AuraEnabled
    public static List<Certification__c> fetchCertificationList(){
        String userName = userInfo.getName();
        List<certification__c> listOfCertifications = [select Id, certificate_id__c, certification_name__c, expiry_date__c from certification__c where contact__r.name = :userName];
        System.debug(listOfCertifications);
        return listOfCertifications;
    }
}