src/retrieveCodeoutput/unpackaged/objects/Contact_Course__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Courses</relationshipLabel>
        <relationshipName>Contact_Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Contact Courses</relationshipLabel>
        <relationshipName>Contact_Courses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Contact Course</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Contact Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/retrieveCodeoutput/unpackaged/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Course Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/FetchMyCoursesController.cls
public class FetchMyCoursesController {
    @AuraEnabled
    public static List<Contact_Course__c> fetchContactCourseList(){
        String userName = userInfo.getName();
        List<contact_course__c> listOfContactCourses = [select Id, course__r.name, course__r.name__c, contact__r.name, course__r.provider__c, start_date__c, end_date__c from contact_course__c where contact__r.name = :userName];
        System.debug(listOfContactCourses);
        return listOfContactCourses;
    }
}