src/retrieveCodeoutput/unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Course_Role__c</fullName>
        <label>Course Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Course_Roles</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/retrieveCodeoutput/unpackaged/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_registered__c</fullName>
        <label>Number registered</label>
        <summaryForeignKey>Contact_Course__c.Course__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trending__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Trending</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Visible_To__c</fullName>
        <defaultValue>&quot;Individual Contributor&quot;</defaultValue>
        <label>Visible To</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Course_Roles</valueSetName>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Course Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Course_Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Individual Contributor</fullName>
        <default>true</default>
        <label>Individual Contributor</label>
    </customValue>
    <customValue>
        <fullName>Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Director</fullName>
    </customValue>
    <customValue>
        <fullName>VP</fullName>
    </customValue>
    <customValue>
        <fullName>SVP</fullName>
    </customValue>
    <customValue>
        <fullName>CXO</fullName>
    </customValue>
    <customValue>
        <fullName>CEO</fullName>
    </customValue>
    <masterLabel>Course Roles</masterLabel>
</GlobalValueSet>

src/retrieveCodeoutput/unpackaged/classes/TrendingCoursesController.cls
public with sharing class TrendingCoursesController {
    @AuraEnabled
    public static list<Course__c> fetchTrendingCourseList(){
        User u = [select id, name, contact.id from user where id = :userInfo.getUserId() limit 1];
        System.debug(u.name);
        Contact c = [select id, course_role__c from contact where id = :u.contact.id limit 1];
        System.debug(c.course_role__c);
        List<course__c> listOfCourses = [select Id, name, name__c, number_registered__c, provider__c, start_date__c, end_date__c 
                                         from course__c where visible_to__c includes (:c.Course_Role__c) order by trending__c desc limit 5];
        System.debug(listOfCourses);
        return listOfCourses;
    }
}