src/retrieveCodeoutput/unpackaged/objects/Exam_Instance__c.object
<CustomObject>
    <description>This holds details of one exam taken by a student</description>
    <fields>
        <fullName>Descriptive_Name__c</fullName>
        <label>Descriptive Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Test_Taker__c</fullName>
        <label>Test Taker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Exams</relationshipLabel>
        <relationshipName>Exam_Instances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time_Taken__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Time Taken</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>fCorrect__c</fullName>
        <label>Correct</label>
        <summarizedField>Exam_Results_Detail__c.fCorrect__c</summarizedField>
        <summaryForeignKey>Exam_Results_Detail__c.My_Exam__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>fNetScore__c</fullName>
        <formula>if ( (fCorrect__c &lt; (( fIncorrect__c -  fOmit__c )/4)), 0, (fCorrect__c - (( fIncorrect__c -  fOmit__c )/4)) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>fTtotal__c</fullName>
        <label>Total</label>
        <summaryForeignKey>Exam_Results_Detail__c.My_Exam__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>My Exam</label>
    <nameField>
        <label>Exam Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Exams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ExamInstanceWrapper.cls
global class ExamInstanceWrapper implements Comparable {
        public Exam_Instance__c ei;
        // Constructor
        public ExamInstanceWrapper(Exam_Instance__c e) {
            ei = e;
        }
        // Compare opportunities based on the opportunity amount.
        global Integer compareTo(Object compareTo) {
            // Cast argument to OpportunityWrapper
            ExamInstanceWrapper compareToExam = (ExamInstanceWrapper)compareTo;
            // The return value of 0 indicates that both elements are equal.
            Integer returnValue = 0;
            System.debug('Left:' + ei.start_time__c);
            System.debug('Right:' + compareToExam.ei.start_time__c);
            if (ei.start_time__c > compareToExam.ei.start_time__c) {
                // Set return value to a positive value.
                returnValue = 1;
            } else if (ei.start_time__c < compareToExam.ei.start_time__c) {
                // Set return value to a negative value.
                returnValue = -1;
            }           
            System.debug('Return value:' + returnValue);
            return returnValue;      
        }

        public String getName() { return this.ei.Descriptive_Name__c; }
        public String getTestTaker() { return this.ei.Test_Taker__r.name; }
        public DateTime getStartTime() { return this.ei.start_time__c; }
        public Decimal getTimeTaken() { return this.ei.time_taken__c; }
        public Decimal getDuration() { return this.ei.Duration__c; }
        public Decimal getRawScore() { return this.ei.fCorrect__c; }
        public Decimal getNetScore() { return this.ei.fNetScore__c; }
        public Decimal getTotal() { return this.ei.fTtotal__c; } 
}