src/retrieveCodeoutput/unpackaged/objects/Exam_Instance__c.object
<CustomObject>
    <description>This holds details of one exam taken by a student</description>
    <fields>
        <fullName>Descriptive_Name__c</fullName>
        <label>Descriptive Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Test_Taker__c</fullName>
        <label>Test Taker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Exams</relationshipLabel>
        <relationshipName>Exam_Instances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time_Taken__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Time Taken</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>fCorrect__c</fullName>
        <label>Correct</label>
        <summarizedField>Exam_Results_Detail__c.fCorrect__c</summarizedField>
        <summaryForeignKey>Exam_Results_Detail__c.My_Exam__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>fNetScore__c</fullName>
        <formula>if ( (fCorrect__c &lt; (( fIncorrect__c -  fOmit__c )/4)), 0, (fCorrect__c - (( fIncorrect__c -  fOmit__c )/4)) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>fTtotal__c</fullName>
        <label>Total</label>
        <summaryForeignKey>Exam_Results_Detail__c.My_Exam__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>My Exam</label>
    <nameField>
        <label>Exam Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Exams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/retrieveCodeoutput/unpackaged/classes/ExamInstanceListController.cls
public with sharing class ExamInstanceListController {
    // ApexPages.StandardSetController must be instantiated
    // for standard list controllers
    public ApexPages.StandardSetController setCon {
        get {
            String uName = UserInfo.getName();
            if(setCon == null) {
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [SELECT id, descriptive_name__c, test_taker__r.name, start_time__c, 
                     time_taken__c, duration__c, fCorrect__c, fNetScore__c, fTtotal__c
                     FROM Exam_Instance__c WHERE test_taker__r.name = :uName ORDER BY createddate DESC]));
                this.sizeOfPage = 20;
                setCon.setPageSize(this.sizeOfPage);
            }
            return setCon;
        }
        set;
    }
    
    public List<Exam_Instance__c> getExamInstances() {
        return setCon.getRecords();
    }
    
    public Integer sizeOfPage { get; set; }
    
    public void next() {
        setcon.next();
    }
    
    public void previous() {
        setcon.previous();
    }

    public Integer pageNumber {
        get {
            return setCon.getPageNumber();
        }
        set;
    }
    
    public Integer resultSize {
        get {
            return setCon.getResultSize();
        }
        set;
    }

    public Integer pageSize {
        get {
            return setCon.getPageSize();
        }
        set;
    }
    
    public void setSize() {
        setCon.setPageSize(this.sizeOfPage);
    }

    // indicates whether there are more records after the current page set.
    public Boolean hasNext {
        get {
            return setCon.getHasNext();
        }
        set;
    }

    // indicates whether there are more records before the current page set.
    public Boolean hasPrevious {
        get {
            return setCon.getHasPrevious();
        }
        set;
    }

    /*    
    public String localTime {
        get {
            //System.debug(ApexPages.currentPage().getParameters().get('utc_dt'));
            //Datetime dt = DateTime.parse(ApexPages.currentPage().getParameters().get('utc_dt'));
            //System.debug(dt);
            //return dt.format('MM/dd/yyyy hh:mm zz');  
            String d = ApexPages.currentPage().getParameters().get('utc_dt');
            return d;
            //return 'hello';         
        }
        set;
    }
    */
}