src/retrieveCodeoutput/unpackaged/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Custom_Tag_Key_1__c</fullName>
        <label>Custom Tag Key 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Tag_Key_2__c</fullName>
        <label>Custom Tag Key 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Tag_Value_1__c</fullName>
        <label>Custom Tag Value 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Tag_Value_2__c</fullName>
        <label>Custom Tag Value 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Difficulty__c</fullName>
        <label>Difficulty</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Difficulty</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flex_Tag_1__c</fullName>
        <label>Flex Tag 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flex_Tag_2__c</fullName>
        <label>Flex Tag 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flex_Tag_4__c</fullName>
        <label>Flex Tag 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flex_Tag_5__c</fullName>
        <label>Flex Tag 5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subjects__c</fullName>
        <label>Subjects</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subject</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <description>Comma separated values</description>
        <label>Tags</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Topics__c</fullName>
        <label>Topics</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Topic</valueSetName>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/retrieveCodeoutput/unpackaged/globalValueSets/Difficulty.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <default>true</default>
        <label>0</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <masterLabel>Difficulty</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Subject.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SAT</fullName>
    </customValue>
    <customValue>
        <fullName>ACT</fullName>
    </customValue>
    <customValue>
        <fullName>AP Math</fullName>
    </customValue>
    <customValue>
        <fullName>AP English</fullName>
    </customValue>
    <customValue>
        <fullName>GRE</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Geography</fullName>
    </customValue>
    <customValue>
        <fullName>Logic</fullName>
    </customValue>
    <customValue>
        <fullName>Math</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>TOEFL</fullName>
    </customValue>
    <customValue>
        <fullName>Operational Excellence</fullName>
    </customValue>
    <masterLabel>Subject</masterLabel>
</GlobalValueSet>

src/retrieveCodeoutput/unpackaged/globalValueSets/Topic.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Algebra</fullName>
    </customValue>
    <customValue>
        <fullName>Algebra.Complex-Numbers</fullName>
    </customValue>
    <customValue>
        <fullName>Algebra.Fractions</fullName>
    </customValue>
    <customValue>
        <fullName>Calculus</fullName>
    </customValue>
    <customValue>
        <fullName>Calculus.Differentiation</fullName>
    </customValue>
    <customValue>
        <fullName>Calculus.Differentiation.Limits</fullName>
    </customValue>
    <customValue>
        <fullName>Calculus.Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Calculus.Integration.By-Parts</fullName>
    </customValue>
    <customValue>
        <fullName>English.Grammar</fullName>
    </customValue>
    <customValue>
        <fullName>English.Reading-Comprehension</fullName>
    </customValue>
    <customValue>
        <fullName>English.Writing</fullName>
    </customValue>
    <customValue>
        <fullName>Geometry</fullName>
    </customValue>
    <customValue>
        <fullName>Geometry.Pythagoras</fullName>
    </customValue>
    <customValue>
        <fullName>Aptitude</fullName>
    </customValue>
    <customValue>
        <fullName>Vocabulary</fullName>
    </customValue>
    <customValue>
        <fullName>General Knowledge</fullName>
    </customValue>
    <customValue>
        <fullName>Lean</fullName>
    </customValue>
    <masterLabel>Topic</masterLabel>
</GlobalValueSet>

src/retrieveCodeoutput/unpackaged/classes/createTags.cls
public class createTags {
    public static void doCreate2(Question__c q) {
        JSONGenerator gen = JSON.createGenerator(true);
        
        //place the first topic in flex_tag_1
        List<String> topics = new List<String>();
        if (q.topics__c != null) {
            topics = q.topics__c.split(';');
            System.debug('Topics length:' + topics.size());
            q.Flex_Tag_1__c = topics[0];        
        } else {
            q.Flex_Tag_1__c = null;
        }
        
        //place the subject in flex_tag_2
        List<String> subjects = new List<String>();
        if (q.Subjects__c != null) {
            subjects = q.Subjects__c.split(';');
            System.debug('Subjects length:' + subjects.size());
            q.Flex_Tag_2__c = subjects[0];
        } else {
            q.Flex_Tag_2__c = null;
        }
        
        //flex_tag_3..5 unused  (can be used for sub topics)
        
        //place the custom tag 1 and 2 in flex_tag_4 and 5
        if (q.Custom_Tag_Key_1__c != null) {
            q.Flex_Tag_4__c = q.Custom_Tag_Value_1__c;
        } else {
            q.Flex_Tag_4__c = null;
        }
        
        if (q.Custom_Tag_Key_2__c != null) {
            q.Flex_Tag_5__c = q.Custom_Tag_Value_2__c;
        } else {
            q.Flex_Tag_5__c = null;
        }
        
        gen.writeStartObject();
        
        if (topics.size() > 0) {
            gen.writeObjectField('topics', topics);
        }
        
        if (subjects.size() > 0) {
            gen.writeObjectField('subject', subjects);
        }
        
        if (q.Difficulty__c != null) {
            gen.writeStringField('difficulty', q.Difficulty__c);
        }
        
        if (q.Custom_Tag_Key_1__c != null) {
            gen.writeStringField(q.Custom_Tag_Key_1__c, q.Custom_Tag_Value_1__c);
        }
        
        if (q.Custom_Tag_Key_2__c != null) {
            gen.writeStringField(q.Custom_Tag_Key_2__c, q.Custom_Tag_Value_2__c);
        }
        
        gen.writeEndObject();
        
        String tags = gen.getAsString();
        q.Tags__c = tags;
        System.debug('Tags:' + tags);        
    }
}